import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, Profile, TrainingGoal, TrendPoint, Workout } from "./api";

type Tab = "home" | "workout" | "sleep" | "history" | "settings";
const sample = "Bench press\n100x8\n100x8\n100x6";
const goals: { value: TrainingGoal; title: string; description: string }[] = [
  { value: "maintenance", title: "Maintain fitness", description: "Keep your current strength, muscle and routine stable." },
  { value: "strength", title: "Build strength", description: "Prioritize heavier compound lifts and measurable strength progress." },
  { value: "hypertrophy", title: "Build muscle", description: "Prioritize muscle growth, quality volume and controlled effort." },
];

function TrendChart({ points }: { points: TrendPoint[] }) {
  const values = points.map((point) => point.strength_rating);
  if (!values.length || values.some((value) => value === null)) return <div className="empty">Add body weight in Settings to calculate your strength rating.</div>;
  const ratings = values as number[];
  const x = (index: number) => index / Math.max(ratings.length - 1, 1) * 100;
  const y = (rating: number) => 90 - rating * .75;
  const coords = ratings.map((rating, index) => `${x(index)},${y(rating)}`).join(" ");
  const meanX = (ratings.length - 1) / 2, meanY = ratings.reduce((sum, rating) => sum + rating, 0) / ratings.length;
  const variance = ratings.reduce((sum, _, index) => sum + (index - meanX) ** 2, 0);
  const slope = variance ? ratings.reduce((sum, rating, index) => sum + (index - meanX) * (rating - meanY), 0) / variance : 0;
  const trend = `${x(0)},${y(meanY + slope * (0 - meanX))} ${x(ratings.length - 1)},${y(meanY + slope * (ratings.length - 1 - meanX))}`;
  const lastPoint = points[points.length - 1];
  return <div className="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none">{[0, 25, 50, 75, 100].map((rating) => <g key={rating}><line x1="0" y1={y(rating)} x2="100" y2={y(rating)} /><text x="1" y={y(rating) - 2} fill="#8da1c3" fontSize="4">{rating}</text></g>)}<line x1="0" y1="90" x2="100" y2="90" /><line x1="0" y1="15" x2="0" y2="90" /><polyline points={coords} /><polyline className="trend" points={trend} />{ratings.map((rating, index) => <g key={index}><circle cx={x(index)} cy={y(rating)} r="1.8"><title>{`${rating}/100 · ${new Date(points[index].performed_at).toLocaleDateString()}`}</title></circle><text x={x(index)} y={y(rating) - 4} textAnchor="middle" fill="#d8e3f8" fontSize="4">{rating}</text></g>)}</svg><div className="axis"><span>{new Date(points[0].performed_at).toLocaleDateString()}</span><b>Relative strength rating /100</b><span>{new Date(lastPoint.performed_at).toLocaleDateString()}</span></div></div>;
}

function Calendar({ workouts, onSelect }: { workouts: Workout[]; onSelect: (workout: Workout) => void }) {
  const [cursor, setCursor] = useState(new Date());
  const [days, setDays] = useState<number[]>([]);
  useEffect(() => { api.calendar(cursor.getFullYear(), cursor.getMonth() + 1).then(({ workout_days }) => setDays(workout_days)); }, [cursor]);
  const monthStart = new Date(cursor.getFullYear(), cursor.getMonth(), 1), offset = (monthStart.getDay() + 6) % 7;
  const length = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 0).getDate();
  const cells = Array.from({ length: offset + length }, (_, index) => index < offset ? 0 : index - offset + 1);
  const open = (day: number) => { const item = workouts.find((workout) => { const date = new Date(workout.performed_at); return date.getFullYear() === cursor.getFullYear() && date.getMonth() === cursor.getMonth() && date.getDate() === day; }); if (item) onSelect(item); };
  return <section className="calendar"><div className="calendar-head"><button onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() - 1))}>‹</button><b>{cursor.toLocaleString("en", { month: "long", year: "numeric" })}</b><button onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + 1))}>›</button></div><div className="week">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(day => <span key={day}>{day}</span>)}</div><div className="days">{cells.map((day, index) => day ? <button key={index} className={days.includes(day) ? "trained" : ""} onClick={() => open(day)}>{day}</button> : <i key={index} />)}</div></section>;
}

export default function App() {
  const [tab, setTab] = useState<Tab>("home"), [dashboard, setDashboard] = useState<Awaited<ReturnType<typeof api.dashboard>> | null>(null);
  const [note, setNote] = useState(sample), [response, setResponse] = useState(""), [sleep, setSleep] = useState(""), [profile, setProfile] = useState<Profile | null>(null);
  const [workouts, setWorkouts] = useState<Workout[]>([]), [exercises, setExercises] = useState<string[]>([]), [exercise, setExercise] = useState(""), [trend, setTrend] = useState<TrendPoint[]>([]), [detail, setDetail] = useState<{ workout: Workout; sets: { name: string; weight_kg: number; reps: number }[] } | null>(null), [message, setMessage] = useState("");
  const refresh = async () => { const [dash, history, names] = await Promise.all([api.dashboard(), api.workouts(), api.exercises()]); setDashboard(dash); setProfile(dash.profile); setWorkouts(history.workouts); setExercises(names.exercises); setExercise((value) => value || names.exercises[0] || ""); };
  useEffect(() => { refresh().catch((error) => setMessage(error.message)); }, []);
  useEffect(() => { if (exercise) api.trend(exercise).then(({ points }) => setTrend(points)); }, [exercise]);
  const submitWorkout = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); try { const data = await api.analyze(note); setResponse(data.response); setMessage("Workout analyzed and saved."); await refresh(); } catch (error) { setMessage((error as Error).message); } };
  const submitSleep = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api.logSleep(Number(sleep)); setSleep(""); setMessage("Sleep saved."); await refresh(); };
  const submitProfile = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await api.saveProfile(Number(form.get("height")), Number(form.get("weight")), String(form.get("goal")) as TrainingGoal); setMessage("Profile and training goal saved."); await refresh(); };
  const nav = useMemo(() => [["home", "Home"], ["workout", "Workout"], ["sleep", "Sleep"], ["history", "History"], ["settings", "Settings"]] as [Tab, string][], []);
  return <main><aside><div className="brand"><span>AF</span><div><b>AI Fitness</b><small>decision support</small></div></div><nav>{nav.map(([id, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{label}</button>)}</nav><button className="demo" onClick={async () => { await api.clearDemo(); setMessage("Demo data cleared."); await refresh(); }}>Clear demo data</button></aside><div className="content"><header><div><h1>{nav.find(([id]) => id === tab)?.[1]}</h1><p>{message || "Training decisions based on your data."}</p></div><button onClick={() => refresh()}>Refresh</button></header>
    {tab === "home" && <div className="page">{!profile && <form className="card onboarding" onSubmit={submitProfile}><div><h2>Start your training profile</h2><p>Choose a goal first. The assistant will use it for future training decisions.</p></div><div className="goal-grid">{goals.map(goal => <label className="goal" key={goal.value}><input name="goal" type="radio" value={goal.value} defaultChecked={goal.value === "maintenance"} /><b>{goal.title}</b><span>{goal.description}</span></label>)}</div><label>Height (cm)<input name="height" required type="number" /></label><label>Body weight (kg)<input name="weight" required type="number" step="0.1" /></label><button className="primary">Save and continue</button></form>}<div className="stats"><article><small>HEIGHT</small><b>{dashboard?.profile ? `${dashboard.profile.height_cm} cm` : "—"}</b></article><article><small>BODY WEIGHT</small><b>{dashboard?.profile ? `${dashboard.profile.body_weight_kg} kg` : "—"}</b></article><article><small>GOAL</small><b>{profile ? goals.find(goal => goal.value === profile.training_goal)?.title : "—"}</b></article><article><small>LATEST SLEEP</small><b>{dashboard?.latest_sleep_hours ? `${dashboard.latest_sleep_hours} h` : "—"}</b></article></div><section className="advice"><h2>Today’s recommendation</h2><p>{dashboard?.message}</p><div>{dashboard?.suggestions.map(item => <div className="suggestion" key={item.name}><b>{item.name}</b><span>{item.suggested_weight_kg} kg · up to {item.target_reps} reps</span></div>) || "Log a workout to receive suggestions."}</div></section></div>}
    {tab === "workout" && <div className="page two"><form className="card" onSubmit={submitWorkout}><h2>Workout note</h2><p>Paste your completed session. Ctrl+V is supported.</p><textarea value={note} onChange={(event) => setNote(event.target.value)} /><button className="primary">Analyze and save</button></form><section className="response"><h2>Coach response</h2><pre>{response || "Your detailed workout assessment will appear here."}</pre></section></div>}
    {tab === "sleep" && <div className="page"><form className="card compact" onSubmit={submitSleep}><h2>Log sleep</h2><p>Save sleep separately; it will be used in the next workout analysis.</p><input required min="0.1" max="24" step="0.1" type="number" placeholder="Hours slept" value={sleep} onChange={(event) => setSleep(event.target.value)} /><button className="primary">Save sleep</button></form></div>}
    {tab === "history" && <div className="page"><section className="card"><div className="row"><div><h2>Relative strength trend</h2><p>0–100 rating from the best estimated 1RM relative to body weight. Scores are rounded to steps of 5.</p></div><select value={exercise} onChange={(event) => setExercise(event.target.value)}>{exercises.map(name => <option key={name}>{name}</option>)}</select></div><TrendChart points={trend} /></section><Calendar workouts={workouts} onSelect={async (workout) => setDetail({ workout, sets: (await api.details(workout.id)).sets })} /></div>}
    {tab === "settings" && <div className="page"><form className="card compact" key={profile?.weight_updated_at ?? "new"} onSubmit={submitProfile}><h2>Profile and training goal</h2><p>Your goal will guide the future progression engine.</p><label>Training goal<select name="goal" defaultValue={profile?.training_goal ?? "maintenance"}>{goals.map(goal => <option key={goal.value} value={goal.value}>{goal.title}</option>)}</select></label><label>Height (cm)<input name="height" required type="number" defaultValue={profile?.height_cm} /></label><label>Body weight (kg)<input name="weight" required type="number" step="0.1" defaultValue={profile?.body_weight_kg} /></label><button className="primary">Save profile</button></form></div>}
  </div>{detail && <div className="modal" onClick={() => setDetail(null)}><section onClick={(event) => event.stopPropagation()}><button className="close" onClick={() => setDetail(null)}>×</button><h2>{new Date(detail.workout.performed_at).toLocaleString()}</h2><p>{detail.workout.exercises}</p>{Object.entries(detail.sets.reduce<Record<string, string[]>>((all, set) => ({ ...all, [set.name]: [...(all[set.name] || []), `${set.weight_kg}x${set.reps}`] }), {})).map(([name, sets]) => <p key={name}><b>{name}</b>: {sets.join(", ")}</p>)}</section></div>}</main>;
}
